name: Go
on: [ push,pull_request ]
jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - name: tag
        id: tag
        run: |
          version=0.2.0
          tag= basename $version
          echo "AUTO_VERSION=$(echo $tag)" >> $GITHUB_ENV
          echo ::set-output name=AUTO_VERSION::$(basename $version)
          echo ${{steps.tag.outputs.AUTO_VERSION}}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            VERSION=${{steps.tag.outputs.AUTO_VERSION}}
          tags: |
            hb0730/auto-sign:latest
            hb0730/auto-sign:${{steps.tag.outputs.AUTO_VERSION}}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
